const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Cryptography,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Flash.Acts.Flash,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event13_Act4,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event14_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event20_Act3,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event21_Act4,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event26_Act2,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event27_Act3,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event28_Act3,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event29_Act3,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event30_Act3,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsAnyPlaying
	];
};
self.C3_JsPropNameTable = [
	{BGForest: 0},
	{BGSky: 0},
	{Sólido: 0},
	{ChãoReto: 0},
	{ChãoPontaDireita: 0},
	{ChãoPontaEsquerda: 0},
	{EncontroPilarChão: 0},
	{Pilar: 0},
	{PotaPilar: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Flash: 0},
	{Timo: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Parede: 0},
	{ParedeInvisível: 0},
	{ChãoInteiro: 0},
	{ÁreaDeGatilho: 0},
	{ÁreaDeDeGatilho2: 0},
	{BGCave: 0},
	{PedraChão: 0},
	{Direcao: 0},
	{PodeAtacar: 0},
	{EstaMorto: 0},
	{Esmaecer: 0},
	{Inimigo: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{ÁreaDeGatilho3: 0},
	{Texto4: 0},
	{ÁreaDeGatilho4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Áudio: 0},
	{PedraChãoIneiro: 0},
	{PedraPontaBaixoDireia: 0},
	{PedraPontaDireita: 0},
	{PedraParedeDireita: 0},
	{PedraPontaBaixoDireita: 0},
	{Criptografia: 0},
	{PedraChãoBaixo: 0},
	{PedraPontaBaixoEsquerda: 0},
	{PedraPontaEsquerda: 0},
	{PedraParedeEsquerda: 0},
	{Pega: 0},
	{Vida: 0},
	{Chave: 0},
	{Âncora: 0},
	{ContVida: 0},
	{Vidas: 0},
	{PortaFase2: 0},
	{Texto7: 0},
	{FonteDeSprites: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{FonteDeSprites2: 0},
	{Sprite4: 0},
	{TemChaveIcon: 0},
	{FonteDeSprites3: 0},
	{Abismo: 0},
	{AbismoMorte: 0},
	{Jaula: 0},
	{PortaFase3: 0},
	{PortaFase4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{FonteDeSprites4: 0},
	{Sprite8: 0},
	{Texto8: 0},
	{Sprite9: 0},
	{Texto9: 0},
	{Sair: 0},
	{Texto11: 0},
	{Sprite10: 0},
	{Mouse: 0},
	{Jogar: 0},
	{FonteDeSprites5: 0},
	{NumeroVidas: 0},
	{TemChave: 0}
];

self.InstanceType = {
	BGForest: class extends self.ISpriteInstance {},
	BGSky: class extends self.ISpriteInstance {},
	ChãoReto: class extends self.ISpriteInstance {},
	ChãoPontaDireita: class extends self.ISpriteInstance {},
	ChãoPontaEsquerda: class extends self.ISpriteInstance {},
	EncontroPilarChão: class extends self.ISpriteInstance {},
	Pilar: class extends self.ISpriteInstance {},
	PotaPilar: class extends self.ISpriteInstance {},
	Timo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Parede: class extends self.ISpriteInstance {},
	ParedeInvisível: class extends self.ISpriteInstance {},
	ChãoInteiro: class extends self.ISpriteInstance {},
	ÁreaDeGatilho: class extends self.ISpriteInstance {},
	ÁreaDeDeGatilho2: class extends self.ISpriteInstance {},
	BGCave: class extends self.ISpriteInstance {},
	PedraChão: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	ÁreaDeGatilho3: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	ÁreaDeGatilho4: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	PedraChãoIneiro: class extends self.ISpriteInstance {},
	PedraPontaBaixoDireia: class extends self.ISpriteInstance {},
	PedraPontaDireita: class extends self.ISpriteInstance {},
	PedraParedeDireita: class extends self.ISpriteInstance {},
	PedraPontaBaixoDireita: class extends self.ISpriteInstance {},
	Criptografia: class extends self.IInstance {},
	PedraChãoBaixo: class extends self.ISpriteInstance {},
	PedraPontaBaixoEsquerda: class extends self.ISpriteInstance {},
	PedraPontaEsquerda: class extends self.ISpriteInstance {},
	PedraParedeEsquerda: class extends self.ISpriteInstance {},
	Vida: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	ContVida: class extends self.ISpriteInstance {},
	Vidas: class extends self.ITextInstance {},
	PortaFase2: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TemChaveIcon: class extends self.ISpriteInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	Abismo: class extends self.ISpriteInstance {},
	AbismoMorte: class extends self.ISpriteInstance {},
	Jaula: class extends self.ISpriteInstance {},
	PortaFase3: class extends self.ISpriteInstance {},
	PortaFase4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	FonteDeSprites4: class extends self.ISpriteFontInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Sair: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Jogar: class extends self.ITextInstance {},
	FonteDeSprites5: class extends self.ISpriteFontInstance {}
}